# Generated by Django 4.1.5 on 2023-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('reciver', models.CharField(blank=True, max_length=200, null=True)),
                ('whosend', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=20000, null=True)),
                ('created', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, db_index=True,
                 max_length=200, null=True, unique=True)),
            ],
        ),
    ]
