# Generated by Django 4.1.5 on 2023-01-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, null=True, unique=True),
        ),
    ]
