# Generated by Django 4.1.5 on 2023-01-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='voicerecord',
            field=models.FileField(blank=True, null=True, upload_to='audios'),
        ),
    ]
