# Generated by Django 4.1.5 on 2023-01-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chat_voicerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='voicerecord',
        ),
    ]
