# Generated by Django 4.1.5 on 2023-01-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chat_voicerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='voicerecord',
            field=models.FileField(blank=True, default='11', null=True, upload_to='audios'),
        ),
    ]
